# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Study' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources', '~> 3.0'
    pod 'Alamofire'
    pod 'RxAlamofire'
    pod 'ObjectMapper', '~> 3.3'
    pod 'Moya'
    pod 'Result'
    pod 'Moya-ObjectMapper'
    pod 'MJRefresh'
    pod 'HandyJSON'
    pod 'Moya/RxSwift'
end
